require_relative "lib/query_lens/version"

Gem::Specification.new do |spec|
  spec.name        = "query_lens"
  spec.version     = QueryLens::VERSION
  spec.authors     = ["Bryan Beshore"]
  spec.email       = ["bryan.beshore@gmail.com"]
  spec.homepage    = "https://github.com/bryanbeshore/query_lens"
  spec.summary     = "Natural language SQL query builder for Rails, powered by AI"
  spec.description = "A mountable Rails engine that lets users write natural language questions and get SQL queries generated by AI (OpenAI, Anthropic, Gemini, Ollama, and more via RubyLLM), executed against their database, with results displayed in a single interface."
  spec.license     = "MIT"

  spec.required_ruby_version = ">= 3.2.0"

  spec.metadata["homepage_uri"] = spec.homepage
  spec.metadata["source_code_uri"] = spec.homepage
  spec.metadata["changelog_uri"] = "#{spec.homepage}/blob/main/CHANGELOG.md"

  spec.files = Dir.chdir(File.expand_path(__dir__)) do
    Dir["{app,config,db,lib}/**/*", "MIT-LICENSE", "Rakefile", "README.md"]
  end

  spec.add_dependency "rails", ">= 7.1"
  spec.add_dependency "ruby_llm", ">= 1.0"

  spec.add_development_dependency "sqlite3"
  spec.add_development_dependency "minitest"
  spec.add_development_dependency "webmock"
end
